### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by Raynos** [isaacs/json-stringify-safe#13]
There are a whole bunch of fixes but no new versions.

**Comment by moll** [comment]
Yeah, I was waiting for someone else to confirm the rewrite doesn't affect them negatively, but I take it no news is good news. I'll put out a new (minor or patch) version, so feel free to depend on `>= 5 < 6` and you'll get it automatically.

**Comment by moll** [comment]
v5.0.1 is now released. ;-)
