### ISSUE TITLE
Missing semicolon breaks JS obfuscation

### ISSUE THREAD

**Issue by danielmohacsi** [isaacs/json-stringify-safe#25]
It appears to me that you have to terminate every statement before the unary `~` operator. Otherwise you will end up having syntax errors if you remove the newlines from the code.

I don't want to start a flamewar about semicolons being good or bad, I just see that in this case, line 18 & 19 should be ending with semicolons, otherwise the code breaks if you use webpack-js-obfuscator.

**Comment by Marsup** [comment]
Minifiers are supposed to be aware of ASI, otherwise that's a bug on their part.

**Comment by moll** [comment]
Hey!

I was about to write the same thing, @Marsup. :) Uglify2, I believe, does it correctly. Perhaps check that out, @danielmohacsi.

**Comment by danielmohacsi** [comment]
Thank you for the suggestion, @moll, but I need to obfuscate the code, uglification is not enough for my purposes. There's a slight difference, and [js-obfuscator](https://javascriptobfuscator.com/Javascript-Obfuscator.aspx) is a standard way to obfuscate code. If I try to obfuscate your code with this tool, I get syntax errors because of the missing semicolons.
I am fully aware of ASI standards, and you are free to use whatever coding standards you like, but I would keep this issue here for folks who face the same problems.

**Comment by moll** [comment]
You can also look into Google Closure Compiler with advanced optimizations. It'll also rename object properties which is more than the Obfuscator tool does that you linked to. The latter seems as silly as the classic "convert source to base64" tactics PHP guys employed years back. :P

I'll close this issue as there's nothing actionable to do right now. Feel free to carry on the convo. ;)
