### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by SimonSchick** [isaacs/json-stringify-safe#27]
I wrote some typings for use in our own project, I don't have time to create a PR but I felt like dropping them here:

```
declare module 'json-stringify-safe' {
    namespace stringify {
        export type CycleReplacer = (key: string, value: any) => string;
        export type Replacer = (key: string, value: any) => any;

        export function getSerialize(replacer?: Replacer, cycleReplacer?: CycleReplacer): any;
    }

    function stringify(
        obj: object,
        replacer?: stringify.Replacer,
        space?: string | number,
        cycleReplacer?: stringify.CycleReplacer,
    ): string;

    export = stringify;
}
```

**Comment by moll** [comment]
Thank you! I'll update the README at some unspecified moment to link to your type signatures. I don't use Typescript myself, so I don't what else to do. :P

**Comment by SimonSchick** [comment]
@moll the idea is to add them to the package 😛

**Comment by MarkHerhold** [comment]
@SimonSchick you can also publish to [@types](https://www.npmjs.com/~types) but a PR might make more sense

**Comment by SimonSchick** [comment]
Closed via https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19026
