### ISSUE TITLE
feature request: deserialize

### ISSUE THREAD

**Issue by oprogramador** [isaacs/json-stringify-safe#32]
It would be good to be able to not only stringify an object with circular references using this lib but also deserialize the obtained string, obtaining an object being the same as the original object (another object in JS memory but with the same values and references working in the same way).

Something like `parse` in this https://github.com/WebReflection/flatted

I request a feature here because https://github.com/WebReflection/flatted creates a string which is not so easy to read for humans.

**Comment by moll** [comment]
Hey!

I suspect parsing circular references back out would could be slightly out of scope for a library that's named JSON *Stringify*. :P I would be open to standardizing on the circular reference syntax, however, so anyone could write their own parser that would work with JSON Stringify Safe's output.

**Comment by oprogramador** [comment]
Yeah, it would be good to implement another library - a deserializer compatible with this library.

**Comment by moll** [comment]
Well, keep me in the loop and good luck in advance! I'll close this issue here as right now there's nothing to do, but we can open it once there's something actionable. :)
