### ISSUE TITLE
I get a syntax error

### ISSUE THREAD

**Issue by arthurmelton** [isaacs/json-stringify-safe#34]
OS: `Arch`
Node Version: `v16.3.0`
Json-stringify-safe vesion: `5.0.1`
Parent pakage: `Request`

Error
```
node_modules/json-stringify-safe/stringify.js:19
            var thisPos = stack.indexOf(this) ~thisPos ? stack.splice(thisPos + 1) : stack.push(this) ~thisPos ? keys.splice(thisPos, Infinity, key) : keys.push(key)
                                              ^

SyntaxError: Unexpected token '~'
```

Weird part:
It works fine on windows but not on linux.

**Comment by arthurmelton** [comment]
I was being dumb sorry

**Comment by moll** [comment]
Glad to hear you found the cause! I presume line endings got messed up.

**Comment by arthurmelton** [comment]
> Glad to hear you found the cause! I presume line endings got messed up.

Yea it did I accidentally js-beautify it and it messed those up
