### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by wparad** [isaacs/json-stringify-safe#38]
Still haven't figured out how this could be the case, but getting this error `RangeError: Invalid string length`

**Comment by moll** [comment]
Hey! Do you have an example code snippet that raises this?

**Comment by wparad** [comment]
I haven't been able to narrow it down yet, but I think the error is related to a problem that the object doesn't have a toJSON defined on it. Specifically it fails trying to log a VueJS 2.6/2.7 component. It's pretty complex to try to get it to log, I'm okay if you close this issue, but I wanted to create it for posterity.

**Comment by moll** [comment]
Sure, we can close it. I suspect it has nothing to do with json-stringify-safe, though. It'd probably arise just from calling `JSON.stringify`, too, and perhaps is a Vue specific error...

**Comment by wparad** [comment]
Could be a vue old that incorrectly implemented toJSON, but somehow I doubt that.

**Comment by moll** [comment]
Well, if you track this down, let me know! I'll close the issue until that as you suggested. ;)
