### ISSUE TITLE
false positive for sibling (not-circular) references

### ISSUE THREAD

**Issue by proppy** [isaacs/json-stringify-safe#9]
```
var safeStringify = require('json-stringify-safe')

var obj = { foo: 'bar' };

console.log(safeStringify({
    a: obj,
    b: obj
}));


console.log(JSON.stringify({
    a: obj,
    b: obj
}));
```

Will produce the following ouput:
```
{"a":{"foo":"bar"},"b":"[Circular ~.a]"}
{"a":{"foo":"bar"},"b":{"foo":"bar"}}
```

It seems to identify multiple sibling references to the same object as circulars.

**Comment by jupiter** [comment]
+1

**Comment by moll** [comment]
Oops, time flies. I'll get to it, @jupiter. ;)

**Comment by moll** [comment]
Comrades,

I copied the [implementation](https://github.com/moll/js-must/blob/master/lib/inspect.js) from [Must.js](https://github.com/moll/js-must), perked it up a little and added a full test suite.
Would y'all mind giving it a spin and see if it does everything you imagined it should?
There's a [CHANGELOG](https://github.com/isaacs/json-stringify-safe/blob/master/CHANGELOG.md), but in summary it just doesn't report false positives any more.

Thanks a bunch!

**Comment by moll** [comment]
v5.0.1 is now released which I should fix this issue. ;-)
